creation of config files for enigmas
auchan-squid-game/auchan-squid-game pull request #45
Opened 2021-10-30 09:58 UTC by amine-yamouni

2021-10-31 19:21 UTC, fduquesne requested changes
Some little changes to make 🔥

2021-10-31 19:21 UTC, fduquesne commented on src/enigmas.json
> +      "idEnigma": "5466",
Juste "id" suffira

2021-10-31 19:21 UTC, fduquesne commented on src/enigmas.json
> +    }
ce serait bien d'avoir une `startDate` et une `endDate` (la `endDate` est intéressante pour éviter de faire des calculs de dates directement dans le code)

2021-11-01 09:33 UTC, amine-yamouni commented on src/enigmas.json
> +      "idEnigma": "5466",
Done

2021-11-01 09:34 UTC, amine-yamouni commented on src/enigmas.json
> +    }
Done. En fait mon fichier ne s'était pas commit. Je sais pas ce que j'avais fait mais tout est corrigé

2021-11-01 11:01 UTC, fduquesne approved these changes
Review OK ✔️

2021-11-01 11:02 UTC, merged