Response validation
auchan-squid-game/auchan-squid-game pull request #46
Opened 2021-10-31 02:41 UTC by thomasoup

2021-11-02 20:15 UTC, fduquesne requested changes
Some little changes to make

2021-11-02 20:15 UTC, fduquesne commented on src/services/user-services.js
> +    return get(ref(db, `/users/${userId}/`));
Ta promesse te revoie une snapshot. Ca signifie que tu vas devoir faire `getUser(uid).then(userSnap => { const user = userSnap.val(); ... });`  
Pour éviter la gestion de la snapshot dans les actions, tu peux faire :  
```javascript
return get(ref(db, `/users/${userId}/`)).then(userSnap => userSnap.val());
```

2021-11-02 20:15 UTC, fduquesne commented on src/services/user-services.js
> +    return update(ref(db), updates);
Je pense que tu peux simplifier avec :  
```javascript
updateUserPointsOnApprove(userId, totalPoints, accumulation) {
  return update(ref(db, `/users/${userId}`), {totalPoints, accumulation});
},
```
A vérifier car je n'en suis pas sur.

2021-11-02 20:15 UTC, fduquesne commented on src/services/user-services.js
> +    return update(ref(db), updates);
Je pense que tu peux simplifier avec :  
```javascript
  return update(ref(db, `/users/${userId}`), {accumulation:0});
```
A vérifier car je n'en suis pas sur.

2021-11-02 20:15 UTC, fduquesne commented on src/store/actions.js
> +   *
Ligne vide non utile

2021-11-02 20:15 UTC, fduquesne commented on src/store/mutations.js
> +  [types.SET_ANSWERS_TO_CHECK](state, { answerId, userAnswerInfos }) {
J'aurais plutot appelé cette mutation `ADD_ANSWER_TO_CHECK`

2021-11-02 20:15 UTC, fduquesne commented on src/store/mutations.js
> +  [types.REMOVE_ANSWER_FROM_ANSWER_TO_CHECK](state, { answerId, userAnswerInfos }) {
Pour faire plus court : `REMOVE_ANSWER_TO_CHECK`

2021-11-02 20:15 UTC, fduquesne commented on src/store/actions.js
> +
Ligne vide inutile.

2021-11-02 20:15 UTC, fduquesne commented on src/store/actions.js
> +      const user = dataSnapshot.val();
A éviter, voir commentaire au dessus.

2021-11-02 20:15 UTC, fduquesne commented on src/store/mutations.js
> +const enigmasJsonFile = require('../enigmas.json');
Utiliser l'import ES6 et simplifier le nom de la variable: `import enigmas from '@/enigmas.json';`

2021-11-02 20:15 UTC, fduquesne commented on src/views/AdministationView/EnigmaSection.vue
> +        answersToCheck: this.$store.state.answersToCheck,
Plutot utilisé un computed pour aller chercher une valeur dans le state.

2021-11-02 20:15 UTC, fduquesne commented on src/views/AdministationView/EnigmaSection.vue
> +  <div v-for="(value, id) in answersToCheck" :key="id">
Mettre `enigma` plutot que `value`

2021-11-03 19:47 UTC, thomasoup commented on src/services/user-services.js
> +        return userValues.answers && Object.values(userValues.answers).some(answer => answer.isApproved === undefined);
Je voulais faire ça au début mais le soucis c'est que, quand une réponse est rejetée, elle sera égale à `False` dans la BDD du coup en faisant un `!answer.isApproved`, est-ce qu'on ne risque pas de récupérer aussi les réponses rejetée et qui ne sont plus à checker?

2021-11-03 20:47 UTC, thomasoup commented on src/store/mutations.js
> +const enigmasJsonFile = require('../enigmas.json');
Yes pas de soucis je fais ça. Par contre, du coup à al ligne 30 ça fait enigmas.enigmas :)

2021-11-03 21:06 UTC, fduquesne commented on src/services/user-services.js
> +        return userValues.answers && Object.values(userValues.answers).some(answer => answer.isApproved === undefined);
En effet !

2021-11-03 21:17 UTC, fduquesne requested changes
Some little changes 😊

2021-11-03 21:17 UTC, fduquesne commented on src/services/user-services.js
> +    });
Simplifiable :  
```javascript
return get(ref(db, `/users/${userId}/`)).then(userSnap => userSnap.val());
```

2021-11-03 21:17 UTC, fduquesne commented on src/store/actions.js
> +  approveResponse({ commit }, payload) {
Utiliser le destructuring : remplacer `payload` par `{answer, id}`

2021-11-03 21:17 UTC, fduquesne commented on src/store/actions.js
> +  rejectResponse({ commit }, payload) {
Utiliser le destructuring : remplacer `payload` par `{answer, id}`

2021-11-03 21:17 UTC, fduquesne commented on src/store/actions.js
> +    userServices.updateAnswerResultOnApproveOrOnReject(payload.answer.userId, payload.id, false).then(() => {
Dans la méthode `approveResponse` tu attends la réponse de `updateUserPointsOnReject` avant de faire `updateAnswerResultOnApproveOrOnReject` alors qu'ici non. Il y a une raison à ça? Si non, ce serait bien d'uniformiser le développement.

2021-11-03 22:12 UTC, thomasoup commented on src/store/actions.js
> +    userServices.updateAnswerResultOnApproveOrOnReject(payload.answer.userId, payload.id, false).then(() => {
Yes tu as raison, c'est mieux d'uniformiser et je garde la même façon que l'autre méthode. Car comme ça si la première promesse est en échec le reste n'est pas tenté.

2021-11-04 05:27 UTC, fduquesne approved these changes
Great work ✔️

2021-11-04 05:27 UTC, merged